### PR TITLE
First version of the unfinished form

### PR DESCRIPTION
**Pull request by qaptivator**
tried making some ui for the patcher, as well as tried converting it to a csproj.
you already did that for me so i copied the fields from the newer version to here.
also made a solution file for this.
now gitignore also includes some visual studio stuff like .vs or obj

### CODE REVIEW

**Comment by qaptivator** [comment]
oops accidentally removed the PublishSingleFile tag from csproj

**Comment by qaptivator** [comment]
conflicts still didn't resolve ok

**Comment by DT-is-not-available** [comment]
Why is it that we need a visual studio solution? Again I feel as though visual studio is overkill, especially with this small of a project, and I have yet to run into a problem that can't just be solved with dotnet. My desktop is still giving me an installation error when trying to install visual studio, so I am literally incapable of editing some of these files through normal means. If there is a reason we have to have visual studio for this, I will keep working on getting it installed, but I've not run into any issues without it so far.

I'll take a look at the remaining merge conflicts.

**Comment by qaptivator** [comment]
visual studio solution may be useful to people who will want to contribute using visual studio or other IDE, like i do.
you still can compile projects from IDE or from CLI, it doesn't matter.

**Comment by DT-is-not-available** [comment]
You don't need to use vs solutions to keep using visual studio to edit or compile the project. cpatcher.csproj is already set up to automatically include UndertaleModLib. Also, the problem isn't whether or not I can build the codebase with or without it. How should I go about editing the UI of the patcher then? Because looking at the output visual studio has given, I would need to edit the MainWindow.Designer.cs file in the exact way visual studio expects it to be loaded in, otherwise I run the risk of breaking it for visual studio users.

So again, is there a reason we need to have a visual studio solution for this to work? If we can set it up so that one does not need to have visual studio installed to _easily_ edit all the files, I am fine with that.

**Comment by qaptivator** [comment]
Ok, i get your point. Solution isn't really necessary, it's not required for the thing to work, mostly so that visual studio won't create it every time. And about the designer, i think the solution to that would be to just probably write the components as you usually do, without the usage of designer and generated .designer.cs files. The application is pretty simple on it's own so there's not gonna be much ui. A bit later i will change these mentioned things.

**Comment by DT-is-not-available** [comment]
Everything looks good, I'm gonna go ahead and merge this now. I will work on getting stuff to be functional in the next few days.

**Pull request merged**
